### ISSUE TITLE
Error command docker-compose up --build airflow-init 

### ISSUE THREAD

**Issue by mbiombani** [ismaildawoodjee/nifi-data-pipeline#1]
Attaching to airflow-init
airflow-init         | ....................
airflow-init         | ERROR! Maximum number of retries (20) reached.
airflow-init         |
airflow-init         | Last check result:
airflow-init         | $ airflow db check
airflow-init         | Unable to load the config, contains a configuration error.
airflow-init         | Traceback (most recent call last):
airflow-init         |   File "/usr/local/lib/python3.8/pathlib.py", line 1288, in mkdir
airflow-init         |     self._accessor.mkdir(self, mode)
airflow-init         | FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/logs/scheduler/2022-04-27'
airflow-init         |
airflow-init         | During handling of the above exception, another exception occurred:
airflow-init         |
airflow-init         | Traceback (most recent call last):
airflow-init         |   File "/usr/local/lib/python3.8/logging/config.py", line 563, in configure
airflow-init         |     handler = self.configure_handler(handlers[name])
airflow-init         |   File "/usr/local/lib/python3.8/logging/config.py", line 744, in configure_handler
airflow-init         |     result = factory(**kwargs)
airflow-init         |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 47, in __init__
airflow-init         |     Path(self._get_log_directory()).mkdir(parents=True, exist_ok=True)
airflow-init         |   File "/usr/local/lib/python3.8/pathlib.py", line 1292, in mkdir
airflow-init         |     self.parent.mkdir(parents=True, exist_ok=True)
airflow-init         |   File "/usr/local/lib/python3.8/pathlib.py", line 1288, in mkdir
airflow-init         |     self._accessor.mkdir(self, mode)
airflow-init         | PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/scheduler'
airflow-init         |
airflow-init         | The above exception was the direct cause of the following exception:
airflow-init         |
airflow-init         | Traceback (most recent call last):
airflow-init         |   File "/home/airflow/.local/bin/airflow", line 5, in <module>
airflow-init         |     from airflow.__main__ import main
airflow-init         |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py", line 47, in <module>
airflow-init         |     settings.initialize()
airflow-init         |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py", line 501, in initialize
airflow-init         |     LOGGING_CLASS_PATH = configure_logging()
airflow-init         |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/logging_config.py", line 74, in configure_logging
airflow-init         |     raise e
airflow-init         |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/logging_config.py", line 69, in configure_logging
airflow-init         |     dictConfig(logging_config)
airflow-init         |   File "/usr/local/lib/python3.8/logging/config.py", line 808, in dictConfig
airflow-init         |     dictConfigClass(config).configure()
airflow-init         |   File "/usr/local/lib/python3.8/logging/config.py", line 570, in configure
airflow-init         |     raise ValueError('Unable to configure handler '
airflow-init         | ValueError: Unable to configure handler 'processor'
airflow-init         |
airflow-init exited with code 1

**Comment by ismaildawoodjee** [comment]
I believe you are getting two errors. The first one is `FileNotFoundError`, probably because the `logs` and `plugins` folders are not created yet. Create them with `mkdir logs` and `mkdir plugins`. The second error is `PermissionError`, so after you create the folders, you need to change their permissions with `chmod 755 logs` and `chmod 755 plugins`. This might clarify: [workflow](https://github.com/ismaildawoodjee/nifi-data-pipeline/blob/main/.github/workflows/workflow.yml)

**Comment by mbiombani** [comment]
I tried, but still 

airflow-init         | PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/scheduler'

**Comment by ismaildawoodjee** [comment]
Try doing `sudo chmod -R 777 <folder>` for `dags`, `logs` and `plugins` after you have deleted everything and recloned this repo: [Stackoverflow reference](https://stackoverflow.com/questions/59412917/errno-13-permission-denied-when-airflow-tries-to-write-to-logs). Also don't forget to do `echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=0" > .env` as specified in the [Airflow docs](https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#initializing-environment). The 777 permissions are discouraged for security reasons however.
